import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Privacy.com addon inserts 'data-extension-installed="2.4.6"' on <body> tag, triggering hydration error.
    // TODO Test with Privacy addon disabled or in another browser when app is ready.
    // <html lang="en" suppressHydrationWarning={true}>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar />
        <div className="flex justify-center items-center min-h-screen">
          <div className="w-full max-w-4xl p-4 bg-white dark:bg-gray-800 shadow-md rounded-lg">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
